/// DO NOT EDIT THIS FILE! ///
#[cfg(test)]
mod tests{
    use crate::{count_tacos, execute_me1};

    #[test]
    fn test_execute_me1() {
        assert_eq!(execute_me1(), "There are 6 tacos!".to_string());
    }

    #[test]
    fn test_count_tacos() {
        let taco_box: [Option<&str>; 10] = [
            Some("Beef taco"),
            None,
            None,
            None,
            Some("Beef taco"),
            None,
            None,
            Some("Fruite taco"),
            Some("Veggie taco"),
            None,
        ];
        assert_eq!(count_tacos(&taco_box), 4)
    }

    #[test]
    fn test_count_tacos_1() {
        let taco_box: [Option<&str>; 10] = [
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        ];
        assert_eq!(count_tacos(&taco_box), 0)
    }

    #[test]
    fn test_count_tacos_2() {
        let taco_box: [Option<&str>; 10] = [
            Some("Fruite taco"),
            Some("Fruite taco"),
            Some("Fruite taco"),
            Some("Fruite taco"),
            Some("Fruite taco"),
            Some("Fruite taco"),
            Some("Fruite taco"),
            Some("Fruite taco"),
            Some("Fruite taco"),
            Some("Fruite taco"),
        ];
        assert_eq!(count_tacos(&taco_box), 10)
    }

}