/// DO NOT EDIT THIS FILE! ///
#[cfg(test)]
mod tests{
    use crate::{total_stat, CritDmg, CritRate, Dmg, Stamina};

    #[test]
    fn test_total_stat() {
        let (Dmg(dmg), CritRate(cr), CritDmg(cd), Stamina(stam)) = total_stat();
        assert_eq!(dmg, 2480);
        assert_eq!(cr, 29.73);
        assert_eq!(cd, 120.45);
        assert_eq!(stam, 75);
    }

}